### ISSUE TITLE
Support HTML tags?

### ISSUE THREAD

**Issue by rauschma** [hikikones/Lazycard#21]
Thanks for this app!

I’d like to generate `.lazytopic` files and there is one feature I’m missing: HTML tags.

My use is is color:

```md
<span style="color:green">手</span>
```

If there is another way of coloring text, then that would work for me, too.

**Comment by hikikones** [comment]
No problem!

Ah yes, this should just be a matter of enabling HTML parsing. Just pushed a new version with it, and it seems to work. 👍

**Comment by rauschma** [comment]
Cool!

**Comment by rauschma** [comment]
Works!

**Comment by hikikones** [comment]
Good to hear!
