### ISSUE TITLE
best way to import cards?

### ISSUE THREAD

**Issue by rowe-morehouse** [hikikones/Lazycard#22]
Lazycard is great, I love it! … One of the cleanest spaced repetition apps I have seen lately. Nice job!

I've got some files that are formatted for import into Anki. They are `.txt` with a simple `|` delimiter for front/back. I attached a file here for your reference. 

**What is the best way to get these files into your `.lazycard` json file format so that I can import them into the app?**

Your export to HTML feature is really slick, and so is the `save` feature from the exported HTML. You design and styles are looking great. 👍 

[anki_format_template.txt](https://github.com/hikikones/Lazycard/files/5399221/anki_format_template.txt)

**Comment by hikikones** [comment]
Thank you very much 😄 

The following Python snippet seems to do the job:

```python
import json

cards = []

with open("anki_format_template.txt") as file:
    for line in file:
        if line == "\n":
            continue

        front, back = line.split("|")
        card = { "front": front, "back": back }
        cards.append(card)

topic = {
    "name": "topic",
    "cards" : cards
}

with open("topic.lazytopic", "w") as file:  
    json.dump(topic, file)
```

This produces the `topic.lazytopic` file which Lazycard can import 👍

**Comment by hikikones** [comment]
Just released a new version that allows you to import Anki topics that have been exported as [plain text files](https://docs.ankiweb.net/#/exporting?id=text-files) where cards are separated by a newline `\n` and the fields (front and back) are separated by a tab `\t`.
