### ISSUE TITLE
Which SR algorithm?

### ISSUE THREAD

**Issue by Positron010** [hikikones/Lazycard#29]
Hi,
Great job! Thanks for the great app! Could you please state which Spaced Repetition algorithm does Lazycard use? 

Thanks!

**Comment by hikikones** [comment]
Hi there! Glad you like it. Lazycard actually uses no SR algorithm in particular (such as SM-2). It simply follows the Fibonacci sequence. That is, the days until next review are determined by the term of the sequence. A successful recall uses the next term, and unsuccessful uses the previous.

You can see the implementation in [SRS.ts](https://github.com/hikikones/Lazycard/blob/master/src/renderer/controller/SRS.ts#L4).
