### ISSUE TITLE
Sorry to flood your issues but just wanted to say thanks :)

### ISSUE THREAD

**Issue by ghost** [hikikones/Lazycard#33]
Seriously, it's has a simplistic UI and doesn't require fiddling around with like Anki does and works exactly how i'd want a flashcard app to work!

**Comment by hikikones** [comment]
Glad you enjoy it! And yeah, while Anki *is* incredible, it is also a bit of a pain to use, hence Lazycard was born. :-)

**Comment by ghost** [comment]
Ooh sidenote - if i get some time i'd like to help contribute on the app a bit so if you have any tasks that you don't plan on doing but would like to add then feel free to throw 'em this way - although no guarentee on that (just picked up typescript a day ago and am also busy working on a game 😅)

**Comment by hikikones** [comment]
I don't have any plans for Lazycard currently, but feel free to add anything that you would like to have :)

**Comment by ghost** [comment]
Ah cool cheers bud - and best of luck :)
